//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTests.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSiteList", ReplyAction="http://tempuri.org/IService/GetSiteListResponse")]
        ChordsInterface.Api.Container<ChordsInterface.Chords.SiteList> GetSiteList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSiteList", ReplyAction="http://tempuri.org/IService/GetSiteListResponse")]
        System.Threading.Tasks.Task<ChordsInterface.Api.Container<ChordsInterface.Chords.SiteList>> GetSiteListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSite", ReplyAction="http://tempuri.org/IService/GetSiteResponse")]
        ChordsInterface.Api.Container<ChordsInterface.Chords.Site> GetSite(int siteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSite", ReplyAction="http://tempuri.org/IService/GetSiteResponse")]
        System.Threading.Tasks.Task<ChordsInterface.Api.Container<ChordsInterface.Chords.Site>> GetSiteAsync(int siteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSystemList", ReplyAction="http://tempuri.org/IService/GetSystemListResponse")]
        ChordsInterface.Api.Container<ChordsInterface.Chords.SystemList> GetSystemList(int siteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSystemList", ReplyAction="http://tempuri.org/IService/GetSystemListResponse")]
        System.Threading.Tasks.Task<ChordsInterface.Api.Container<ChordsInterface.Chords.SystemList>> GetSystemListAsync(int siteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetInstrumentList", ReplyAction="http://tempuri.org/IService/GetInstrumentListResponse")]
        ChordsInterface.Api.Container<ChordsInterface.Chords.InstrumentList> GetInstrumentList(int systemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetInstrumentList", ReplyAction="http://tempuri.org/IService/GetInstrumentListResponse")]
        System.Threading.Tasks.Task<ChordsInterface.Api.Container<ChordsInterface.Chords.InstrumentList>> GetInstrumentListAsync(int systemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMeasurements", ReplyAction="http://tempuri.org/IService/GetMeasurementsResponse")]
        string GetMeasurements(int siteID, int streamIndex, int hoursBack);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMeasurements", ReplyAction="http://tempuri.org/IService/GetMeasurementsResponse")]
        System.Threading.Tasks.Task<string> GetMeasurementsAsync(int siteID, int streamIndex, int hoursBack);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateMeasurement", ReplyAction="http://tempuri.org/IService/CreateMeasurementResponse")]
        string CreateMeasurement(ChordsInterface.Chords.Measurement measurement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateMeasurement", ReplyAction="http://tempuri.org/IService/CreateMeasurementResponse")]
        System.Threading.Tasks.Task<string> CreateMeasurementAsync(ChordsInterface.Chords.Measurement measurement);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ServiceTests.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ServiceTests.ServiceReference.IService>, ServiceTests.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ChordsInterface.Api.Container<ChordsInterface.Chords.SiteList> GetSiteList() {
            return base.Channel.GetSiteList();
        }
        
        public System.Threading.Tasks.Task<ChordsInterface.Api.Container<ChordsInterface.Chords.SiteList>> GetSiteListAsync() {
            return base.Channel.GetSiteListAsync();
        }
        
        public ChordsInterface.Api.Container<ChordsInterface.Chords.Site> GetSite(int siteID) {
            return base.Channel.GetSite(siteID);
        }
        
        public System.Threading.Tasks.Task<ChordsInterface.Api.Container<ChordsInterface.Chords.Site>> GetSiteAsync(int siteID) {
            return base.Channel.GetSiteAsync(siteID);
        }
        
        public ChordsInterface.Api.Container<ChordsInterface.Chords.SystemList> GetSystemList(int siteID) {
            return base.Channel.GetSystemList(siteID);
        }
        
        public System.Threading.Tasks.Task<ChordsInterface.Api.Container<ChordsInterface.Chords.SystemList>> GetSystemListAsync(int siteID) {
            return base.Channel.GetSystemListAsync(siteID);
        }
        
        public ChordsInterface.Api.Container<ChordsInterface.Chords.InstrumentList> GetInstrumentList(int systemID) {
            return base.Channel.GetInstrumentList(systemID);
        }
        
        public System.Threading.Tasks.Task<ChordsInterface.Api.Container<ChordsInterface.Chords.InstrumentList>> GetInstrumentListAsync(int systemID) {
            return base.Channel.GetInstrumentListAsync(systemID);
        }
        
        public string GetMeasurements(int siteID, int streamIndex, int hoursBack) {
            return base.Channel.GetMeasurements(siteID, streamIndex, hoursBack);
        }
        
        public System.Threading.Tasks.Task<string> GetMeasurementsAsync(int siteID, int streamIndex, int hoursBack) {
            return base.Channel.GetMeasurementsAsync(siteID, streamIndex, hoursBack);
        }
        
        public string CreateMeasurement(ChordsInterface.Chords.Measurement measurement) {
            return base.Channel.CreateMeasurement(measurement);
        }
        
        public System.Threading.Tasks.Task<string> CreateMeasurementAsync(ChordsInterface.Chords.Measurement measurement) {
            return base.Channel.CreateMeasurementAsync(measurement);
        }
    }
}
